In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
amz_df = pd.read_csv("./Data/amazon_delivery.csv")
amz_df

,Order_ID,Agent_Age,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Delivery_Time,Category
0,ialx566343618,37,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,11:45:00,Sunny,High,motorcycle,Urban,120,Clothing
1,akqg208421122,34,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,19:50:00,Stormy,Jam,scooter,Metropolitian,165,Electronics
2,njpu434582536,23,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,08:45:00,Sandstorms,Low,motorcycle,Urban,130,Sports
3,rjto796129700,38,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,18:10:00,Sunny,Medium,motorcycle,Metropolitian,105,Cosmetics
4,zguw716275638,32,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,13:45:00,Cloudy,High,scooter,Metropolitian,150,Toys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43734,jlxf819993117,30,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35:00,11:45:00,Windy,High,motorcycle,Metropolitian,160,Home
43735,aevx342135787,21,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,19:55:00,20:10:00,Windy,Jam,motorcycle,Metropolitian,180,Jewelry
43736,xnek760674819,30,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,23:50:00,00:05:00,Cloudy,Low,scooter,Metropolitian,80,Home
43737,cynl434665991,20,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,13:35:00,13:40:00,Cloudy,High,motorcycle,Metropolitian,130,Kitchen
43738,nsyz997960170,23,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,17:10:00,17:15:00,Fog,Medium,scooter,Metropolitian,180,Cosmetics

# Removing Some Columns

In [4]:
amz_df.drop(columns=['Agent_Age',"Category"],inplace=True)#droping irrelevent columns

In [5]:
amz_df['Agent_Rating'] = amz_df['Agent_Rating'].fillna(amz_df['Agent_Rating'].mean())
amz_df

,Order_ID,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Delivery_Time
0,ialx566343618,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,11:45:00,Sunny,High,motorcycle,Urban,120
1,akqg208421122,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,19:50:00,Stormy,Jam,scooter,Metropolitian,165
2,njpu434582536,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,08:45:00,Sandstorms,Low,motorcycle,Urban,130
3,rjto796129700,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,18:10:00,Sunny,Medium,motorcycle,Metropolitian,105
4,zguw716275638,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,13:45:00,Cloudy,High,scooter,Metropolitian,150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43734,jlxf819993117,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35:00,11:45:00,Windy,High,motorcycle,Metropolitian,160
43735,aevx342135787,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,19:55:00,20:10:00,Windy,Jam,motorcycle,Metropolitian,180
43736,xnek760674819,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,23:50:00,00:05:00,Cloudy,Low,scooter,Metropolitian,80
43737,cynl434665991,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,13:35:00,13:40:00,Cloudy,High,motorcycle,Metropolitian,130
43738,nsyz997960170,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,17:10:00,17:15:00,Fog,Medium,scooter,Metropolitian,180

# Performing Ordinal Encoding

In [6]:
print(amz_df['Traffic'].unique()) #to check  all the unique values in the column
print(amz_df['Weather'].unique())
amz_df['Traffic'] = amz_df['Traffic'].str.strip()#removing extra spaces so that we don't get problems during mapping
amz_df['Weather'] = amz_df['Weather'].str.strip()
ordinal_map = {'Low': 1, 'Medium': 2, 'High': 3, 'Jam':4, 'NaN': 3}
ord_map = {'Sunny' :1, 'Cloudy':1, 'Windy':1 ,'Stormy': 3, 'Sandstorms' :2, 'Fog':4, 'nan':3}

ordinal_encoded_df = amz_df.copy()
ordinal_encoded_df['Traffic_Ordinal'] = amz_df['Traffic'].map(ordinal_map)#.fillna(-1) ## # or another placeholder value
ordinal_encoded_df['Weather_Ordinal'] = amz_df['Weather'].map(ord_map)
#ordinal_encoded_df.drop(['Traffic','Order_ID','Vehicle','Area','Weather', 'Order_Time','Pickup_Time','Order_Date'],axis=1, inplace= True)#Removing some more irrelevant 
ordinal_encoded_df['Delivery_Time'] = ordinal_encoded_df['Delivery_Time'].fillna(ordinal_encoded_df['Delivery_Time'].mean())
ordinal_encoded_df

['High ' 'Jam ' 'Low ' 'Medium ' 'NaN ']
['Sunny' 'Stormy' 'Sandstorms' 'Cloudy' 'Fog' 'Windy' nan]

,Order_ID,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Delivery_Time,Traffic_Ordinal,Weather_Ordinal
0,ialx566343618,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,11:45:00,Sunny,High,motorcycle,Urban,120,3,1.0
1,akqg208421122,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,19:50:00,Stormy,Jam,scooter,Metropolitian,165,4,3.0
2,njpu434582536,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,08:45:00,Sandstorms,Low,motorcycle,Urban,130,1,2.0
3,rjto796129700,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,18:10:00,Sunny,Medium,motorcycle,Metropolitian,105,2,1.0
4,zguw716275638,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,13:45:00,Cloudy,High,scooter,Metropolitian,150,3,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43734,jlxf819993117,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35:00,11:45:00,Windy,High,motorcycle,Metropolitian,160,3,1.0
43735,aevx342135787,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,19:55:00,20:10:00,Windy,Jam,motorcycle,Metropolitian,180,4,1.0
43736,xnek760674819,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,23:50:00,00:05:00,Cloudy,Low,scooter,Metropolitian,80,1,1.0
43737,cynl434665991,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,13:35:00,13:40:00,Cloudy,High,motorcycle,Metropolitian,130,3,1.0
43738,nsyz997960170,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,17:10:00,17:15:00,Fog,Medium,scooter,Metropolitian,180,2,4.0

In [7]:
ordinal_encoded_df.to_csv("routeCity.csv",index=False)